In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("air_quality_updated.csv")
df = pd.DataFrame(data)

In [3]:
df.columns

Index(['Unnamed: 0', 'date_time', 'PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3',
       'TEMP', 'PRES', 'DEWP', 'RAIN', 'wd', 'WSPM', 'station',
       'PM2.5_category', 'TEMP_Category', 'day_of_week', 'Weekend_Weekday',
       'activity'],
      dtype='str')

In [5]:
df.agg({
    'PM2.5': ['min', 'max', 'mean', 'nunique'],
    'PM2.5_category': ['min', 'max', 'nunique']
})

              PM2.5  PM2.5_category
min        2.000000            Good
max      821.000000  Very unhealthy
mean      83.477884             NaN
nunique  676.000000               6

In [6]:
def max_minus_min(s):
    return s.max()-s.min()

max_minus_min(df['TEMP'])

np.float64(58.400000000000006)

In [7]:
df[['PM2.5', 'TEMP']].agg(['min', 'max', max_minus_min])

               PM2.5  TEMP
min              2.0 -16.8
max            821.0  41.6
max_minus_min  819.0  58.4

In [8]:
df[['PM2.5', 'PM10']].min(axis=1)

0         9.0
1         4.0
2         4.0
3         5.0
4         3.0
         ...
95680     9.0
95681    10.0
95682    18.0
95683    15.0
95684    15.0
Length: 95685, dtype: float64

In [9]:
df[['PM2.5', 'PM10']].mean(axis=1)

0         9.0
1         4.0
2         4.0
3         5.0
4         4.5
         ...
95680     9.0
95681    19.5
95682    25.0
95683    28.5
95684    32.5
Length: 95685, dtype: float64

In [10]:
df[['PM2.5', 'PM10']].sum(axis=1)

0        18.0
1         8.0
2         8.0
3        10.0
4         9.0
         ...
95680    18.0
95681    39.0
95682    50.0
95683    57.0
95684    65.0
Length: 95685, dtype: float64

In [13]:
df.groupby(by='PM2.5_category').groups

{'Good': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 72, 73, 74, 75, 76, 78, 81, 82, 83, 168, 169, 201, 202, 203, 205, 206, 208, 238, 275, 276, 277, 278, 282, 283, 286, 287, 370, 371, 411, 412, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 462, 463, 464, 465, 466, 467, 468, 495, 507, 513, 514, 515, 520, 521, 522, 523, 524, 525, 527, 528, 529, 534, 535, 536, 624, 636, 637, 638, ...], 'Hazardous': [137, 139, 144, 145, 146, 147, 148, 149, 150, 151, 152, 158, 159, 160, 161, 162, 163, 164, 165, 166, 170, 175, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 364, 1127, 1128, 1129, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1563, 1564, 1569, 1782, 1803, 1804, 2021, 2022, 2023, 3229, 3230, 3231, 3232, 3233, 3234, 3247, 3248, 3253, 3254, 3255, 3256, 3257, 3258, 3259, 3268, 3385, 3386, 3387, 3388, 3389, 3390, 3391, 3392, 3393, 3394, 3395, 3396, ...], 'Moderate': [16, 18, 19, 28, 33, 34, 35, 36, 61, 71, 77, 79, 80, 84, 85, 86, 87, 196, 197, 198, 199, 200, 204, 207, 209, 210, 211, 212, 213, 214, 215, 216, 217, 279, 280, 281, 284, 285, 288, 289, 290, 292, 410, 446, 447, 461, 469, 470, 512, 516, 517, 518, 519, 526, 530, 531, 532, 533, 537, 538, 623, 625, 626, 629, 630, 631, 632, 633, 634, 635, 719, 720, 721, 722, 723, 727, 736, 737, 738, 739, 747, 748, 749, 750, 751, 752, 779, 780, 783, 784, 785, 786, 787, 788, 789, 791, 792, 793, 794, 795, ...], 'Unhealthy': [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 63, 64, 65, 67, 68, 69, 70, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 123, 167, 172, 177, 179, 180, 181, 182, 185, 186, 187, 188, 189, 190, 192, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 239, 240, 241, 242, 243, 244, 245, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 264, 265, 266, 267, 268, 269, 270, 271, 272, ...], 'Unhealthy for sensitive groups': [37, 38, 60, 62, 88, 89, 178, 183, 184, 193, 194, 195, 218, 219, 220, 221, 274, 291, 293, 294, 372, 373, 429, 430, 431, 432, 433, 434, 435, 436, 437, 539, 627, 628, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 717, 718, 753, 776, 777, 778, 781, 782, 868, 869, 870, 871, 872, 876, 877, 878, 879, 882, 883, 886, 903, 904, 926, 927, 928, 929, 930, 939, 940, 941, 959, 961, 962, 965, 974, 985, 988, 989, 990, 991, 992, 993, 994, 1004, 1005, 1006, 1026, 1027, 1028, 1031, 1032, 1033, 1034, 1035, ...], 'Very unhealthy': [66, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 138, 140, 141, 142, 143, 153, 154, 155, 156, 157, 171, 173, 174, 176, 191, 246, 247, 262, 263, 318, 319, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 365, 366, 367, 368, 369, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 408, ...]}

In [14]:
df.groupby(by='PM2.5_category').groups.keys()

dict_keys(['Good', 'Hazardous', 'Moderate', 'Unhealthy', 'Unhealthy for sensitive groups', 'Very unhealthy'])

In [19]:
df.groupby(by='PM2.5_category').get_group('Good')

,Unnamed: 0,date_time,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station,PM2.5_category,TEMP_Category,day_of_week,Weekend_Weekday,activity
0,0,2013-03-01 00:00:00,9.0,9.0,3.0,17.0,300.0,89.0,-0.5,1024.5,-21.4,0.0,NNW,5.7,Dongsi,Good,Very Cold,Friday,Weekday,Stay inside
1,1,2013-03-01 01:00:00,4.0,4.0,3.0,16.0,300.0,88.0,-0.7,1025.1,-22.1,0.0,NW,3.9,Dongsi,Good,Very Cold,Friday,Weekday,Stay inside
2,2,2013-03-01 05:00:00,4.0,4.0,9.0,25.0,300.0,78.0,-2.4,1027.5,-21.3,0.0,NW,2.4,Dongsi,Good,Very Cold,Friday,Weekday,Stay inside
3,3,2013-03-01 06:00:00,5.0,5.0,10.0,29.0,400.0,67.0,-2.5,1028.2,-20.4,0.0,NW,2.2,Dongsi,Good,Very Cold,Friday,Weekday,Stay inside
4,4,2013-03-01 07:00:00,3.0,6.0,12.0,40.0,400.0,52.0,-1.4,1029.5,-20.4,0.0,NNW,3.0,Dongsi,Good,Very Cold,Friday,Weekday,Stay inside
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95676,95676,2017-02-28 11:00:00,7.0,18.0,3.0,23.0,400.0,82.0,13.3,1016.0,-12.8,0.0,NW,3.3,Tiantan,Good,Warm,Tuesday,Weekday,Go outside
95677,95677,2017-02-28 12:00:00,8.0,17.0,2.0,19.0,300.0,87.0,12.9,1015.4,-14.9,0.0,NW,3.3,Tiantan,Good,Warm,Tuesday,Weekday,Go outside
95678,95678,2017-02-28 13:00:00,6.0,8.0,2.0,18.0,300.0,89.0,14.0,1014.5,-15.0,0.0,NNW,2.9,Tiantan,Good,Warm,Tuesday,Weekday,Go outside
95680,95680,2017-02-28 15:00:00,9.0,9.0,2.0,22.0,300.0,91.0,15.4,1013.0,-15.0,0.0,NNW,3.3,Tiantan,Good,Warm,Tuesday,Weekday,Go outside
95681,95681,2017-02-28 16:00:00,10.0,29.0,3.0,21.0,300.0,94.0,14.9,1012.6,-15.4,0.0,NW,2.1,Tiantan,Good,Warm,Tuesday,Weekday,Go outside

In [28]:
df.drop(columns='Unnamed: 0', inplace=True)
df['year'] = df['date_time'].astype('datetime64[ns]').dt.year
df.sort_values('date_time').groupby('year').first()

,date_time,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station,PM2.5_category,TEMP_Category,day_of_week,Weekend_Weekday,activity
year,,,,,,,,,,,,,,,,,,,
2013,2013-03-01 00:00:00,9.0,9.0,3.0,17.0,300.0,89.0,-0.5,1024.5,-21.4,0.0,NNW,5.7,Dongsi,Good,Very Cold,Friday,Weekday,Stay inside
2014,2014-01-01 01:00:00,66.0,154.0,40.0,81.0,1500.0,7.0,-1.1,1008.8,-13.0,0.0,WNW,1.2,Dongsi,Unhealthy,Very Cold,Wednesday,Weekday,Stay inside
2015,2015-01-01 00:00:00,3.0,14.0,15.0,29.0,600.0,33.0,-7.0,1026.0,-23.8,0.0,ENE,0.9,Dongsi,Good,Very Cold,Thursday,Weekday,Stay inside
2016,2016-01-01 00:00:00,200.0,209.0,31.0,98.0,3400.0,2.0,-2.5,1024.5,-8.2,0.0,NNE,1.1,Dongsi,Very unhealthy,Very Cold,Friday,Weekday,Stay inside
2017,2017-01-01 00:00:00,423.0,509.0,5.0,102.0,5900.0,2.0,-4.7,1022.1,-6.1,0.0,ENE,1.0,Tiantan,Hazardous,Very Cold,Sunday,Weekend,Stay inside

In [32]:
df.groupby('TEMP_Category').size()

TEMP_Category
Cold         19154
Hot          19189
Very Cold    19156
Very Hot     19043
Warm         19143
dtype: int64

In [35]:
df['TEMP_Category'].value_counts(sort=False)

TEMP_Category
Very Cold    19156
Cold         19154
Warm         19143
Hot          19189
Very Hot     19043
Name: count, dtype: int64

In [37]:
df['quarter'] = df['date_time'].astype('datetime64[ns]').dt.quarter

In [44]:
df[['PM2.5', 'TEMP', 'quarter']].groupby('quarter').mean()

              PM2.5       TEMP
quarter
1         94.069142   2.899613
2         70.628065  20.437886
3         65.190722  25.092483
4        104.022908   6.427893

In [46]:
df.groupby('quarter')[['PM2.5', 'TEMP']].mean()

              PM2.5       TEMP
quarter
1         94.069142   2.899613
2         70.628065  20.437886
3         65.190722  25.092483
4        104.022908   6.427893

In [48]:
df.groupby('quarter')[['PM2.5', 'TEMP']].describe()

           PM2.5                                                         \
           count        mean         std  min   25%   50%    75%    max
quarter
1        23786.0   94.069142   97.763512  3.0  16.0  64.0  139.0  821.0
2        23766.0   70.628065   55.120769  2.0  30.0  57.0   97.0  533.0
3        24089.0   65.190722   51.676983  3.0  24.0  52.0   94.0  375.0
4        24044.0  104.022908  105.065528  3.0  21.0  69.0  158.0  741.0

            TEMP
           count       mean       std   min   25%   50%   75%   max
quarter
1        23786.0   2.899613  6.719962 -16.8  -1.8   2.0   6.9  26.2
2        23766.0  20.437886  6.577351  -0.1  16.0  20.8  25.2  41.6
3        24089.0  25.092483  5.014595   6.4  21.7  25.1  28.8  39.3
4        24044.0   6.427893  7.362627 -11.0   0.6   5.8  12.2  28.4

In [50]:
df.groupby('quarter')[['PM2.5', 'TEMP']].agg(['min', 'max'])

        PM2.5         TEMP
          min    max   min   max
quarter
1         3.0  821.0 -16.8  26.2
2         2.0  533.0  -0.1  41.6
3         3.0  375.0   6.4  39.3
4         3.0  741.0 -11.0  28.4

In [51]:
df.columns

Index(['date_time', 'PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3', 'TEMP', 'PRES',
       'DEWP', 'RAIN', 'wd', 'WSPM', 'station', 'PM2.5_category',
       'TEMP_Category', 'day_of_week', 'Weekend_Weekday', 'activity', 'year',
       'quarter'],
      dtype='str')

In [52]:
df.groupby('day_of_week')[['PM2.5', 'TEMP', 'RAIN']].agg({
    'PM2.5':['min', 'max', 'mean'],
    'TEMP':'mean',
    'RAIN':'mean'
})

            PM2.5                         TEMP      RAIN
              min    max       mean       mean      mean
day_of_week
Friday        3.0  770.0  86.297504  13.656026  0.084618
Monday        3.0  821.0  76.712301  13.712800  0.060099
Saturday      3.0  767.0  91.335310  13.913513  0.049066
Sunday        2.0  608.0  83.679894  13.784520  0.046537
Thursday      2.0  652.0  82.753128  13.791723  0.047143
Tuesday       3.0  741.0  81.348613  13.470587  0.062619
Wednesday     3.0  628.0  81.996792  13.772449  0.102176

In [53]:
df.groupby(['quarter', 'TEMP_Category'])[['PM2.5', 'TEMP']].mean()

                            PM2.5       TEMP
quarter TEMP_Category
1       Cold            92.376038   5.255577
        Hot             94.577281  20.788082
        Very Cold       94.070465  -2.459695
        Very Hot        17.833333  25.333333
        Warm            99.279817  13.590823
2       Cold            59.876121   7.745623
        Hot             76.560711  21.698941
        Very Cold       34.000000   1.291667
        Very Hot        71.260904  28.338596
        Warm            65.706344  15.014399
3       Cold            26.565217   9.084058
        Hot             63.162094  22.195009
        Very Hot        68.854851  28.980545
        Warm            55.122137  16.405912
4       Cold            92.685972   5.755530
        Hot            119.191781  20.989298
        Very Cold      118.953695  -1.809818
        Very Hot       103.780220  25.906593
        Warm            98.960145  13.888034

In [56]:
df['month'] = df['date_time'].astype('datetime64[ns]').dt.month
df.groupby(['year', 'quarter', 'month'])[ 'TEMP'].agg(['min', 'max'])

                      min        max
year quarter month
2013 1       3      -5.40  22.400000
     2       4      -0.10  29.400000
             5       7.90  35.000000
             6      14.60  35.500000
     3       7      19.80  37.700000
             8      15.40  37.100000
             9       6.40  31.500000
     4       10      0.80  25.900000
             11     -4.60  18.900000
             12     -8.50  15.400000
2014 1       1      -9.90  12.600000
             2     -11.50   9.900000
             3      -5.60  26.200000
     2       4       4.60  30.600000
             5       5.60  41.600000
             6      14.60  37.500000
     3       7      20.40  37.200000
             8      16.90  35.700000
             9      10.80  33.900000
     4       10      2.20  25.500000
             11     -4.00  21.500000
             12    -11.00  12.600000
2015 1       1      -9.00  11.000000
             2     -10.00  13.000000
             3      -7.30  23.600000
     2       4       1.70  31.900000
             5       8.20  33.800000
             6      14.40  34.100000
     3       7      17.00  39.300000
             8      17.80  36.300000
             9      11.60  32.300000
     4       10     -0.30  27.400000
             11     -9.70  20.000000
             12     -9.60  10.000000
2016 1       1     -16.80   8.100000
             2      -9.00  11.800000
             3      -4.40  23.000000
     2       4       5.20  30.400000
             5       6.20  34.000000
             6      15.20  37.300000
     3       7      18.80  37.000000
             8      15.10  36.100000
             9       8.65  31.800000
     4       10     -1.30  28.400000
             11     -7.20  16.100000
             12     -9.30  11.400000
2017 1       1      -9.90   9.166667
             2      -9.70  15.500000